[book]
authors = ["Ariel Abreu"]
language = "en"
multilingual = false
src = "src"
title = "The Acca Architecture Specification"

[output.html]

[output.html.playground]
runnable = false

[output.html.print]
enable = true

[output.pdf]
scale = 0.8

[output.pdf-outline]
like-wkhtmltopdf = true
