[package]
name = "acca-as"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
clap = { version = "4.1.9", features = ["derive"] }
lazy_static = "1.4.0"
pest = "2.5.6"
pest_derive = "2.5.6"
acca-as-proc-macro = { path = "../acca-as-proc-macro" }
